### ISSUE TITLE
Broken link / incorrect formatting on quarks-edge.github.io

### ISSUE THREAD

**Issue by home4slc** [quarks-edge/quarks-edge.github.io#7]
When browsing through the web site: http://quarks-edge.github.io/

If I go to this page:
http://quarks-edge.github.io/quarks.documentation/docs/quarks/committers/
it works, but if I go to the 'Current committers' page it does not:

https://github.com/orgs/quarks-edge/teams/quarkscommitters

[Removed separate issue already covered by another issue in quarks.documentation]

**Comment by kathyssaunders** [comment]
The committers page is not accessible to everyone.  I changed the document to point to the pulse page.  Check http://quarks-edge.github.io/quarks.documentation//docs/quarks/committers/ and see if that works.

**Comment by kathyssaunders** [comment]
Had a github user who is not a committer try this link and it works fine.
